# Generated by Django 4.2.5 on 2023-09-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_van_nbhd'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='van_nbhd',
            table='myapp_van_nbhd',
        ),
    ]
