# Generated by Django 4.2.5 on 2023-09-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_van_nbhd_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van_nbhd',
            name='id',
        ),
        migrations.AddField(
            model_name='van_nbhd',
            name='gid',
            field=models.AutoField( primary_key=True, serialize=False),
        ),
    ]
