# Generated by Django 4.2.5 on 2023-10-03 05:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_van_nbhd_id_van_nbhd_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ca_Nbhd',
            fields=[
                ('gid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
            options={
                'db_table': 'myapp_ca_nbhd',
            },
        ),
    ]
