# Generated by Django 4.2.5 on 2023-10-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='myapp_user',
        ),
    ]
