# Generated by Django 4.2.5 on 2023-11-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_badges_tag_poll_body_poll_comment_count_and_more'),
        ('myapp', '0011_user_location'),
    ]

    operations = [
    ]
