# Generated by Django 4.2.5 on 2023-11-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
