# Generated by Django 4.2.5 on 2023-11-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='location',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='van_nbhd',
            name='gid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
